/*
 * This file is generated by jOOQ.
*/
package com.deco.transbot.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConfigUser implements Serializable {

    private static final long serialVersionUID = 250926689;

    private String username;
    private String langSource;
    private String langTarget;

    public ConfigUser() {}

    public ConfigUser(ConfigUser value) {
        this.username = value.username;
        this.langSource = value.langSource;
        this.langTarget = value.langTarget;
    }

    public ConfigUser(
        String username,
        String langSource,
        String langTarget
    ) {
        this.username = username;
        this.langSource = langSource;
        this.langTarget = langTarget;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getLangSource() {
        return this.langSource;
    }

    public void setLangSource(String langSource) {
        this.langSource = langSource;
    }

    public String getLangTarget() {
        return this.langTarget;
    }

    public void setLangTarget(String langTarget) {
        this.langTarget = langTarget;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ConfigUser (");

        sb.append(username);
        sb.append(", ").append(langSource);
        sb.append(", ").append(langTarget);

        sb.append(")");
        return sb.toString();
    }
}
