/*
 * This file is generated by jOOQ.
*/
package com.deco.transbot.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 45739302;

    private String username;
    private String name;

    public User() {}

    public User(User value) {
        this.username = value.username;
        this.name = value.name;
    }

    public User(
        String username,
        String name
    ) {
        this.username = username;
        this.name = name;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(username);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
