/*
 * This file is generated by jOOQ.
*/
package com.deco.transbot.jooq;


import com.deco.transbot.jooq.tables.ConfigUser;
import com.deco.transbot.jooq.tables.records.ConfigUserRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>transbot</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ConfigUserRecord> KEY_CONFIG_USER_CONFIG_USER_USERNAME_UINDEX = UniqueKeys0.KEY_CONFIG_USER_CONFIG_USER_USERNAME_UINDEX;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ConfigUserRecord> KEY_CONFIG_USER_CONFIG_USER_USERNAME_UINDEX = createUniqueKey(ConfigUser.CONFIG_USER, "KEY_config_user_config_user_username_uindex", ConfigUser.CONFIG_USER.USERNAME);
    }
}
