/*
 * This file is generated by jOOQ.
*/
package com.deco.transbot.jooq;


import com.deco.transbot.jooq.tables.ConfigUser;
import com.deco.transbot.jooq.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Transbot extends SchemaImpl {

    private static final long serialVersionUID = -195054356;

    /**
     * The reference instance of <code>transbot</code>
     */
    public static final Transbot TRANSBOT = new Transbot();

    /**
     * The table <code>transbot.config_user</code>.
     */
    public final ConfigUser CONFIG_USER = com.deco.transbot.jooq.tables.ConfigUser.CONFIG_USER;

    /**
     * The table <code>transbot.user</code>.
     */
    public final User USER = com.deco.transbot.jooq.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Transbot() {
        super("transbot", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            ConfigUser.CONFIG_USER,
            User.USER);
    }
}
