/*
 * This file is generated by jOOQ.
*/
package com.deco.transbot.jooq.tables.daos;


import com.deco.transbot.jooq.tables.Laguage;
import com.deco.transbot.jooq.tables.records.LaguageRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LaguageDao extends DAOImpl<LaguageRecord, com.deco.transbot.jooq.tables.pojos.Laguage, String> {

    /**
     * Create a new LaguageDao without any configuration
     */
    public LaguageDao() {
        super(Laguage.LAGUAGE, com.deco.transbot.jooq.tables.pojos.Laguage.class);
    }

    /**
     * Create a new LaguageDao with an attached configuration
     */
    public LaguageDao(Configuration configuration) {
        super(Laguage.LAGUAGE, com.deco.transbot.jooq.tables.pojos.Laguage.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.deco.transbot.jooq.tables.pojos.Laguage object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.deco.transbot.jooq.tables.pojos.Laguage> fetchById(String... values) {
        return fetch(Laguage.LAGUAGE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.deco.transbot.jooq.tables.pojos.Laguage fetchOneById(String value) {
        return fetchOne(Laguage.LAGUAGE.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.deco.transbot.jooq.tables.pojos.Laguage> fetchByName(String... values) {
        return fetch(Laguage.LAGUAGE.NAME, values);
    }
}
