/*
 * This file is generated by jOOQ.
*/
package com.deco.transbot.jooq.tables.records;


import com.deco.transbot.jooq.tables.ConfigUser;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConfigUserRecord extends TableRecordImpl<ConfigUserRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 2063607836;

    /**
     * Setter for <code>transbot.config_user.username</code>.
     */
    public void setUsername(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>transbot.config_user.username</code>.
     */
    public String getUsername() {
        return (String) get(0);
    }

    /**
     * Setter for <code>transbot.config_user.lang_source</code>.
     */
    public void setLangSource(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>transbot.config_user.lang_source</code>.
     */
    public String getLangSource() {
        return (String) get(1);
    }

    /**
     * Setter for <code>transbot.config_user.lang_target</code>.
     */
    public void setLangTarget(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>transbot.config_user.lang_target</code>.
     */
    public String getLangTarget() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return ConfigUser.CONFIG_USER.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ConfigUser.CONFIG_USER.LANG_SOURCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ConfigUser.CONFIG_USER.LANG_TARGET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLangSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLangTarget();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfigUserRecord value1(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfigUserRecord value2(String value) {
        setLangSource(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfigUserRecord value3(String value) {
        setLangTarget(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfigUserRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConfigUserRecord
     */
    public ConfigUserRecord() {
        super(ConfigUser.CONFIG_USER);
    }

    /**
     * Create a detached, initialised ConfigUserRecord
     */
    public ConfigUserRecord(String username, String langSource, String langTarget) {
        super(ConfigUser.CONFIG_USER);

        set(0, username);
        set(1, langSource);
        set(2, langTarget);
    }
}
