/*
 * This file is generated by jOOQ.
*/
package com.deco.transbot.jooq.tables;


import com.deco.transbot.jooq.Keys;
import com.deco.transbot.jooq.Transbot;
import com.deco.transbot.jooq.tables.records.LaguageRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Laguage extends TableImpl<LaguageRecord> {

    private static final long serialVersionUID = -1545433367;

    /**
     * The reference instance of <code>transbot.laguage</code>
     */
    public static final Laguage LAGUAGE = new Laguage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LaguageRecord> getRecordType() {
        return LaguageRecord.class;
    }

    /**
     * The column <code>transbot.laguage.id</code>.
     */
    public final TableField<LaguageRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(6).nullable(false), this, "");

    /**
     * The column <code>transbot.laguage.name</code>.
     */
    public final TableField<LaguageRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

    /**
     * Create a <code>transbot.laguage</code> table reference
     */
    public Laguage() {
        this("laguage", null);
    }

    /**
     * Create an aliased <code>transbot.laguage</code> table reference
     */
    public Laguage(String alias) {
        this(alias, LAGUAGE);
    }

    private Laguage(String alias, Table<LaguageRecord> aliased) {
        this(alias, aliased, null);
    }

    private Laguage(String alias, Table<LaguageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Transbot.TRANSBOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<LaguageRecord> getPrimaryKey() {
        return Keys.KEY_LAGUAGE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<LaguageRecord>> getKeys() {
        return Arrays.<UniqueKey<LaguageRecord>>asList(Keys.KEY_LAGUAGE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Laguage as(String alias) {
        return new Laguage(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Laguage rename(String name) {
        return new Laguage(name, null);
    }
}
